---
# tasks file for image_builder

- name: Subscribe machines
  include_role:
    name: "{{ role_path }}/../infra-ansible/roles/rhsm"
  when: rhsm_manage | bool

- name: Install Packages
  package:
    name: "{{ yum_packages }}"
    state: present

- name: cockpit service socket
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ systemd_services }}"

- name: firewalld
  firewalld:
    service: cockpit
    state: enabled
    permanent: yes
    immediate: yes

- name: firewalld
  firewalld:
    port: "{{ httpd_host_port }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes

- name: Build Image
  include_tasks: build_image.yaml
  loop: "{{ image_builder_images }}"
  loop_control:
    loop_var: builder_image
