---
# defaults file for image_builder

rhsm_manage: true
blueprints_tmp_directory: /tmp/blueprints
container_image_directory_path: /tmp/container_build

rhsm_repos:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - ansible-2.9-for-rhel-8-x86_64-rpms

yum_packages:
  - firewalld
  - osbuild-composer
  - composer-cli
  - cockpit-composer
  - bash-completion
  - podman

systemd_services:
  - firewalld
  - osbuild-composer.socket
  - cockpit.socket

image_builder_images:
  - name: rfe-ansible
    description: RFE Ansible
    version: 0.0.1
    modules:
      - name: ansible
        version: "*"
      - name: git
        version: "*"

rfe_user: core
rfe_password: edge

rfe_git:
  url: https://github.com/sabre1041/rfe-mgmt-ansible.git
  version: ansible-edge
  playbook_file: playbooks/rfe.yaml

rfe_automation_timer_sync: 60min

httpd_container_port: 80
httpd_host_port: 8000
